export const RECAPTCHA_OPTIONS = Symbol('RECAPTCHA_OPTIONS');

export const RECAPTCHA_VALIDATION_OPTIONS = Symbol('RECAPTCHA_VALIDATION_OPTIONS');

export const RECAPTCHA_HTTP_SERVICE = 'RECAPTCHA_HTTP_SERVICE';
